# Pytorch Training Loop

- A PyTorch training loop is an essential part of building a neural network model, which helps us teach the computer how to make predictions or decisions based on data. By using this loop, we gradually improve our model's accuracy through a process of learning from its mistakes and adjusting.

## Code Examples
### Create a Number Sum Dataset
This dataset has two features—a pair of numbers—and a target value—the sum of those two numbers.

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

In [3]:
class NumberSumDataset(Dataset):

    def __init__(self, data_range=(1, 10)):
        self.numbers = list(range(data_range[0], data_range[1]))

    def __getitem__(self, index):
        numb_len = len(self.numbers)
        number1 = float(self.numbers[index // numb_len])
        number2 = float(self.numbers[index % numb_len])
        sum = number1 + number2

        return torch.tensor([number1, number2]), torch.tensor([sum])

    def __len__(self):
        return len(self.numbers) ** 2

In [5]:
# Inspect the Dataset
dataset = NumberSumDataset(data_range=(1, 100))

for i in range(5):
    print(dataset[i])

(tensor([1., 1.]), tensor([2.]))
(tensor([1., 2.]), tensor([3.]))
(tensor([1., 3.]), tensor([4.]))
(tensor([1., 4.]), tensor([5.]))
(tensor([1., 5.]), tensor([6.]))


# Defining Simple Model

In [7]:
class MLP(nn.Module):

    def __init__(self, input_size):
        super().__init__()
        self.hidden_layer = nn.Linear(input_size, 128)
        self.output_layer = nn.Linear(128, 1)
        self.activation = nn.ReLU()

    def forward(self, x):
        x = self.activation(self.hidden_layer(x))
        return self.output_layer(x)

## Instantiate components needed for training

In [8]:
dataset = NumberSumDataset(data_range=(0, 100))
dataloader = DataLoader(dataset, batch_size=100, shuffle=True)

model = MLP(input_size=2)
loss_function = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

## Creating a Training Loop

In [9]:
for epoch in range(10):
    total_loss = 0.0
    for number_pairs, sums in dataloader:
        predictions = model(number_pairs)
        loss = loss_function(predictions, sums)
        
        loss.backward()         # Perform backpropagation
        optimizer.step()        # Update the paraametes
        optimizer.zero_grad()       # Zero the gradients

        total_loss += loss.item()       # Add the loss for all batches

    
    # Print teh loss for this epoch
    print("Epoch {}: Sum of Batch Losses = {:.5f}".format(epoch, total_loss))


Epoch 0: Sum of Batch Losses = 381409.74857
Epoch 1: Sum of Batch Losses = 5115.26620
Epoch 2: Sum of Batch Losses = 1269.61995
Epoch 3: Sum of Batch Losses = 277.80763
Epoch 4: Sum of Batch Losses = 41.18079
Epoch 5: Sum of Batch Losses = 9.78246
Epoch 6: Sum of Batch Losses = 6.45426
Epoch 7: Sum of Batch Losses = 4.77095
Epoch 8: Sum of Batch Losses = 3.28997
Epoch 9: Sum of Batch Losses = 2.66763


## Trying out the Model

In [12]:
# Testing the model on 3 + 7
model(torch.tensor([3.0, 7.0]))

tensor([10.3971], grad_fn=<ViewBackward0>)